Infrastructure
GLBaseCamp2023/Note-BE pull request #2
Opened 2023-01-14 11:51 UTC by Lithoid

2023-01-14 12:35 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +            if (saving)
А для чого потрібна змінна saving?

2023-01-14 12:39 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +        private DbContext _context;
Ще потрібно додати пропертю _dbSet<T>, а не кожного разу робити в методах _context.Set<T>();

2023-01-14 12:56 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +        public async Task<T> GetItemAsync(Expression<Func<T, bool>>? filter = null, bool tracked = true, string includeProps = null) {
Як на мене, складна логіка для простого метода репозиторія.
По-перше filter - обов'язковий параметр, навіщо ставити йому за замовчуванням null.
Не розумію навіщо Where, коли можна одразу FirstOrDefault(filter), тоді й перевірки на null не потрібно.
На рахунок інклюдів, можна в параметрах приймати який саме інклюд потрібен (або якщо декілька, можна написати свій екстенш метод).
Також ніколи не чув за ситуації , коли нам потрібен був tracking для того, щоб просто отримати entity. Думаю, потрібно вже за замовчуванням додавати до запиту AsNoTracking()

2023-01-14 13:04 UTC, dmmitrenko requested changes

2023-01-14 13:04 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +        public async Task<List<T>> GetAllItemsAsync(Expression<Func<T, bool>> filter = null, string includeProps = null) {
Аналогічно і тут для інклюдів, я би краще приймав ті інклюди які необхідні у вигляді params. Логіка, яка тут інтуїтивно не зрозуміла.

2023-01-14 13:04 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +        public async Task<T> GetItemAsync(Expression<Func<T, bool>>? filter = null, bool tracked = true, string includeProps = null) {
Як на мене, складна логіка для простого метода репозиторія.
По-перше filter - обов'язковий параметр, навіщо ставити йому за замовчуванням null.
Не розумію навіщо Where, коли можна одразу FirstOrDefault(filter), тоді й перевірки на null не потрібно.
На рахунок інклюдів, можна в параметрах приймати який саме інклюд потрібен (або якщо декілька, можна написати свій екстенш метод).
Також ніколи не чув за ситуації , коли нам потрібен був tracking для того, щоб просто отримати entity. Думаю, потрібно вже за замовчуванням додавати до запиту AsNoTracking()

2023-01-14 13:04 UTC, dmmitrenko commented on Evernote.Repositories/Abstract/DbRepository.cs
> +        private DbContext _context;
Ще потрібно додати поле _dbSet, а не кожного разу робити в методах _context.Set();

2023-01-15 09:04 UTC, BaseCampGL2023 commented on Evernote.Context/AppDataContext.cs
> +                        note.HasOne(n => n.User)
I would suggest using ApplyConfiguration and Configs in a separate file.
This is just styling stuff - no need to change

2023-01-15 09:08 UTC, BaseCampGL2023 commented on Evernote.Repositories/Abstract/DbRepository.cs
> +            try {
A little bit strange construction. Better to leave as is without try/catch. Later on in code we may want to react on exception and in this case we would need to always check the output for '-1'

2023-01-26 17:49 UTC, BaseCampGL2023 approved these changes

2023-01-26 20:36 UTC, dmmitrenko approved these changes

2023-02-18 18:20 UTC, lannahirave approved these changes

2023-02-18 18:22 UTC, merged